name: GO-SOPT-Server CI

on:
  push:
    branches: [ "logging-file" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    - name: checkout
      uses: actions/checkout@v3
    
    # 2) JDK 17버전 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # 3) 환경변수 파일 생성
    - name: make application.properties 파일 생성
      run: |
        ## create application.yml
        mkdir ./src/main/resources
        cd ./src/main/resources

        # application.yml 파일 생성
        touch ./application.yml

        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION }}" >> ./application.yml
        
        # application.yml 파일 확인
        cat ./application.yml
      shell: bash
        
    # 이 워크플로우는 gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
      run: ./gradlew build -x test
      
    - name: Build Test Code # test code 실행
      run: ./gradlew test
